#!/usr/bin/env python3
"""Summarize structures generated by the fixed-rise pNAB twist series."""

from __future__ import annotations

import argparse
import csv
import statistics
import sys
from collections import Counter, defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from hexaplex_formation.pdb_utils import chain_ids, load_pdb_atoms, residue_count  # noqa: E402


BASE_ATOMS = {
    "N1", "C2", "N3", "C4", "N5", "C6", "OC2", "OC4", "OC6",
    "C1", "N2", "C3", "N4", "C5", "N6", "NX1", "NX2", "NX3",
}
FIELDS = [
    "model_id", "twist_deg", "rise_A", "atom_count", "residue_count", "chain_count",
    "residue_counts", "inferred_base_layer_count", "adjacent_rise_interval_count",
    "measured_mean_adjacent_rise_A", "measured_adjacent_rise_stdev_A", "notes",
]


def infer_layers(atoms) -> tuple[int, list[float]]:
    by_residue = defaultdict(list)
    for atom in atoms:
        if atom.residue_name in {"CYP", "MEP"} and atom.atom_name in BASE_ATOMS:
            key = (atom.chain_id, atom.residue_number, atom.residue_name)
            by_residue[key].append(atom.z)
    centers = sorted(statistics.mean(values) for values in by_residue.values() if values)
    layers: list[list[float]] = []
    for center in centers:
        if not layers or abs(center - statistics.mean(layers[-1])) > 1.2:
            layers.append([center])
        else:
            layers[-1].append(center)
    means = [statistics.mean(layer) for layer in layers]
    return len(layers), [right - left for left, right in zip(means, means[1:])]


def summarize(path: Path, model_id: str, twist: str, rise: str) -> dict[str, str]:
    atoms = load_pdb_atoms(path)
    residues = {
        (atom.chain_id, atom.residue_number, atom.insertion_code, atom.residue_name)
        for atom in atoms
    }
    counts = Counter(item[3] for item in residues)
    layer_count, intervals = infer_layers(atoms)
    return {
        "model_id": model_id,
        "twist_deg": twist,
        "rise_A": rise,
        "atom_count": str(len(atoms)),
        "residue_count": str(residue_count(atoms)),
        "chain_count": str(len(chain_ids(atoms))),
        "residue_counts": ";".join(f"{name}:{count}" for name, count in sorted(counts.items())),
        "inferred_base_layer_count": str(layer_count),
        "adjacent_rise_interval_count": str(len(intervals)),
        "measured_mean_adjacent_rise_A": f"{statistics.mean(intervals):.9f}" if intervals else "",
        "measured_adjacent_rise_stdev_A": f"{statistics.pstdev(intervals):.9g}" if intervals else "",
        "notes": "Layer count and rise are inferred from clustered CYP/MEP base-atom z centroids.",
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=ROOT / "outputs/pnab_twist_series_rise3p38/pnab_twist_series_manifest.csv")
    parser.add_argument("--out", type=Path, default=ROOT / "outputs/metrics/pnab_twist_series_structure_summary.csv")
    args = parser.parse_args()
    with args.manifest.open(newline="", encoding="utf-8") as handle:
        manifest = list(csv.DictReader(handle))
    rows = []
    for item in manifest:
        if not item["structure_path"]:
            continue
        rows.append(summarize(ROOT / item["structure_path"], item["model_id"], item["twist_deg"], item["rise_A"]))
    args.out.parent.mkdir(parents=True, exist_ok=True)
    with args.out.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=FIELDS, lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)
    print(f"Wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
